from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, KeepTogether, PageBreak
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total page count and draw
    a professional header/footer on each page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # We only draw running headers/footers on page 2 and onwards,
        # or on all pages since it's a short report. Let's draw on all pages.
        
        # Color definitions
        text_color = colors.HexColor("#64748B") # Slate grey
        line_color = colors.HexColor("#E2E8F0") # Light grey
        
        # Draw header
        self.setFont("Helvetica", 8)
        self.setFillColor(text_color)
        self.drawString(54, 750, "RESEARCH PAPER SUMMARY REPORT")
        self.drawRightString(558, 750, datetime.now().strftime("%Y-%m-%d"))
        self.setStrokeColor(line_color)
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Draw footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        self.drawString(54, 40, "Generated by Research Paper Summarizer AI")
        self.line(54, 52, 558, 52)
        
        self.restoreState()

def generate_summary_pdf(summary_data: dict, original_filename: str, output_path: str):
    """
    Compiles structured summary data into a beautifully formatted PDF report.
    
    Inputs:
        summary_data (dict): The structured JSON summary.
        original_filename (str): Name of the source research paper.
        output_path (str): Filepath where the PDF should be written.
    """
    # Create the document template
    # Page size: Letter (8.5 x 11 inches = 612 x 792 points)
    # Margins: 0.75 inch (54 points) all around. Top margin is larger to accommodate running header.
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    # Custom styles
    styles = getSampleStyleSheet()
    
    # Custom Palette
    primary_color = colors.HexColor("#1E1B4B")  # Deep Indigo
    secondary_color = colors.HexColor("#4F46E5") # Royal Purple
    text_dark = colors.HexColor("#0F172A")      # Charcoal dark
    text_mute = colors.HexColor("#475569")      # Muted slate
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=14,
        textColor=text_mute,
        spaceAfter=25
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=secondary_color,
        spaceBefore=18,
        spaceAfter=8,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10.5,
        leading=15,
        textColor=text_dark,
        spaceAfter=10
    )
    
    bullet_style = ParagraphStyle(
        'ReportBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        leftIndent=15,
        firstLineIndent=-10,
        textColor=text_dark,
        spaceAfter=6
    )
    
    fig_title_style = ParagraphStyle(
        'FigTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=primary_color,
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True
    )

    story = []
    
    # 1. Document Header Block
    story.append(Paragraph(summary_data.get("title", "Research Paper Summary"), title_style))
    story.append(Paragraph(f"Original File: {original_filename}  |  Generated on: {datetime.now().strftime('%B %d, %Y')}", meta_style))
    
    # Helper to add section
    def add_section(title, text_content=None, list_content=None):
        story.append(Paragraph(title, h1_style))
        if text_content:
            story.append(Paragraph(text_content, body_style))
        if list_content:
            for item in list_content:
                if item.strip():
                    story.append(Paragraph(f"&bull; {item.strip()}", bullet_style))
        story.append(Spacer(1, 10))
        
    # 2. Add each section sequentially
    # Section 1: Overall Summary
    add_section("1. Overall Summary", text_content=summary_data.get("overall_summary"))
    
    # Section 2: Main Idea
    add_section("2. Main Idea", text_content=summary_data.get("main_idea"))
    
    # Section 3: Problem Being Solved
    add_section("3. Problem Being Solved", text_content=summary_data.get("problem_solved"))
    
    # Section 4: Assumptions
    add_section("4. Assumptions", list_content=summary_data.get("assumptions", []))
    
    # Section 5: Limitations
    add_section("5. Limitations", list_content=summary_data.get("limitations", []))
    
    # Section 6: Results and Conclusion
    add_section("6. Results and Conclusion", text_content=summary_data.get("results_conclusion"))
    
    # Section 7: Real World Impact
    add_section("7. Real World Impact", text_content=summary_data.get("real_world_impact"))
    
    # Section 8: Graphs and Figures Analysis
    graphs_figs = summary_data.get("graphs_figures", [])
    if graphs_figs:
        story.append(Paragraph("8. Graphs and Figures Analysis", h1_style))
        for fig in graphs_figs:
            fig_elements = []
            fig_elements.append(Paragraph(fig.get("title", "Figure"), fig_title_style))
            fig_elements.append(Paragraph(fig.get("explanation", ""), body_style))
            fig_elements.append(Spacer(1, 8))
            story.append(KeepTogether(fig_elements))
    else:
        add_section("8. Graphs and Figures Analysis", text_content="No graphs or figures were detected or analyzed in the document.")

    # Build PDF
    doc.build(story, canvasmaker=NumberedCanvas)
